#!/bin/bash
#Script Variables
HOST='174.138.191.235';
USER='fvnetpro_deb';
PASS='fvnetpro_deb';
DBNAME='fvnetpro_deb';
PORT_TCP='1194';
PORT_UDP='110';
PORT_SSL='443';
OBFS='dxplusdev';
HYSTERIA_TYPE='default';
PORT_VLESS='442';
API_LINK='https://dev.fvnetpro.top/api/authentication';
API_KEY='Dxplusdev';
DOMAIN=mknu.fvnetpro.top
NS=y0k3.fvnetpro.top
404: Not Found